safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: 狼烟
host: hongxiaolong.github.io
desc: 在否定中进步，在思考中成长

custom:
    category:
        tech: tech
        thinking: thinking
        sample: sample

    categories:
      - name:  tech
        title: tech

      - name: thinking
        title: thinking

    scrollingLoadCount: 2                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: hongxiaolong
        desc: 愿风指引你的道路
        email: hongxiaolong.info@gmail.com
        disqus: hongxiaolong                        # Disqus缩略标识
        gcse: 001728465442046369016:yoween5qzfo     # Google自定义搜索标识ID
        github: hongxiaolong                        # GitHub账号
        weibo: http://weibo.com/changingalot/       # 新浪微博
        gravatar: 3b99651ab65e0f96f4bd68075fd1e13c  # Gravatar头像标识
        analytics: UA-81206656-1                    # Google Analytics ID

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: https://en.gravatar.com/avatar/        # Gravatar头像服务器地址
